"""simulate.py -- generated by node_llm_codegen (graph-driven + per-node LLM)."""

import argparse
from pathlib import Path

import pandas as pd


def simulate(df, tariffs, parameters):
    df = df.copy()
    df["Timestamp"] = pd.to_datetime(df["Timestamp"])
    member_type = df["member_type"]
    W_c = df["load"]
    member_id = df["member_id"]
    Timestamp = df["Timestamp"]
    W_g = df["generation"]
    n = parameters.get("n", 122)
    a = parameters.get("a", 0.65)
    d_CG = parameters.get("d_CG", 0.7)
    d_MC = parameters.get("d_MC", 0.5)
    d_EQ = parameters.get("d_EQ", 0.0)
    _tariff_column_ToU = next((c for c in tariffs.columns if str(c).lower() == 'ToU'.lower()), None)
    if _tariff_column_ToU is None:
        raise KeyError("Missing tariff column: " + 'ToU')
    _tariff_map_ToU = tariffs.set_index("time")[_tariff_column_ToU]
    ToU = df["Timestamp"].dt.hour.map(_tariff_map_ToU).astype(float)
    _tariff_column_FiT = next((c for c in tariffs.columns if str(c).lower() == 'FiT'.lower()), None)
    if _tariff_column_FiT is None:
        raise KeyError("Missing tariff column: " + 'FiT')
    _tariff_map_FiT = tariffs.set_index("time")[_tariff_column_FiT]
    FiT = df["Timestamp"].dt.hour.map(_tariff_map_FiT).astype(float)
    q = parameters.get("q", 0.082)
    b = parameters.get("b", 0.65)
    W_gs = df["generation"]*0.1
    # [complex] W_d
    W_d = W_c - W_g
    # [complex] W_net
    _W_gs = df["Timestamp"].map(W_gs) if isinstance(W_gs, pd.Series) and not W_gs.index.equals(df.index) else W_gs
    _q = df["member_id"].map(q) if isinstance(q, pd.Series) and not q.index.equals(df.index) else q
    W_net = (W_c - W_g - _W_gs * _q).fillna(0.0)
    # [complex] Wused_i
    _W_gs = df["Timestamp"].map(W_gs) if not W_gs.index.equals(df.index) else W_gs
    _q = df["member_id"].map(q) if isinstance(q, pd.Series) else q
    Wused_i = pd.DataFrame({"W_c": W_c, "val": W_g + _W_gs * _q}).min(axis=1)
    # [complex] Wused_EC
    _sum_W_c = W_c.groupby(df["Timestamp"]).transform("sum")
    _sum_W_g = W_g.groupby(df["Timestamp"]).transform("sum")
    Wused_EC = pd.concat([_sum_W_c, W_gs + _sum_W_g], axis=1).min(axis=1)
    # [piecewise] CostI
    _tou = ToU if ToU.index.equals(df.index) else df["Timestamp"].map(ToU)
    CostI = W_d.clip(lower=0) * _tou
    # [piecewise] RevI_raw
    _fit_aligned = Timestamp.map(FiT).fillna(0.0)
    RevI_raw = (-W_d).clip(lower=0.0) * _fit_aligned
    # [complex] Sum_W_d
    Sum_W_d = W_d.groupby(df["Timestamp"]).transform("sum")
    # [complex] qS
    _W_net_neg = W_net.where(W_net < 0, 0.0)
    _sum_neg = _W_net_neg.groupby(df["Timestamp"]).transform("sum")
    qS = (_W_net_neg / _sum_neg).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] qD
    _W_net_pos = W_net.clip(lower=0.0)
    _sum_W_net_pos = _W_net_pos.groupby(df["Timestamp"]).transform("sum")
    qD = (
    (_W_net_pos / _sum_W_net_pos)
    .replace([float("inf"), -float("inf")], 0.0)
    .fillna(0.0)
    )
    # [complex] SSI_i
    _ratio = Wused_i / W_c
    SSI_i = _ratio.where(W_c != 0, 1.0).replace([float("inf"), float("-inf")], 1.0).fillna(1.0)
    # [complex] SCI_i
    _denom = W_g + W_gs * q
    SCI_i = (Wused_i / _denom).where(_denom != 0, 1.0)
    SCI_i = SCI_i.replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] SSI_EC
    _sum_W_c = W_c.groupby(df["Timestamp"]).transform("sum")
    SSI_EC = Wused_EC.div(_sum_W_c).where(_sum_W_c != 0, 1.0).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] SCI_EC
    _sum_W_g = W_g.groupby(df["Timestamp"]).transform("sum")
    _W_gs = W_gs if len(W_gs) == len(df) else df["Timestamp"].map(W_gs)
    _denom = _W_gs + _sum_W_g
    SCI_EC = (Wused_EC / _denom).replace([float("inf"), float("-inf")], 1.0).fillna(1.0)
    # [complex] RevI
    _W_gs = W_gs if len(W_gs) == len(df) else df["Timestamp"].map(W_gs)
    _FiT = FiT if len(FiT) == len(df) else df["Timestamp"].map(FiT)
    _W_gs = _W_gs.fillna(0.0)
    _FiT = _FiT.fillna(0.0)
    RevI = (RevI_raw + _W_gs * q * _FiT).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [piecewise] Rev_EC
    _diff = W_gs - Sum_W_d
    Rev_EC = _diff.clip(lower=0) * FiT
    # [piecewise] Cost_EC
    Cost_EC = (Sum_W_d - W_gs).clip(lower=0) * ToU
    # [complex] SSI_EC_avg
    _SSI_EC_hourly = SSI_EC.groupby(df["Timestamp"]).mean()
    SSI_EC_avg = _SSI_EC_hourly.mean()
    # [complex] SCI_EC_avg
    _hourly_SCI_EC = (
    SCI_EC.groupby(df["Timestamp"])
    .first()
    .replace([float("inf"), float("-inf")], 0.0)
    .fillna(0.0)
    )
    _avg_val = _hourly_SCI_EC.mean()
    SCI_EC_avg = pd.Series(_avg_val, index=df.index).fillna(0.0)
    # [complex] PayI
    PayI = CostI - RevI
    # [complex] Pay_EC
    Pay_EC = Cost_EC - Rev_EC
    # [complex] Pay_0
    Pay_0 = PayI.groupby(df["Timestamp"]).transform("sum")
    # [complex] G_EC
    G_EC = Pay_0 - Pay_EC
    # [complex] CS_EC
    CS_EC = (1 - Pay_EC / Pay_0) * 100
    CS_EC = CS_EC.where(Pay_0 != 0, 0.0).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] G_EQ
    G_EQ = (G_EC / n).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] G_G
    G_G = q * G_EC
    # [complex] G_C
    _sum_W_c = W_c.groupby(df["Timestamp"]).transform("sum")
    G_C = (W_c / _sum_W_c).replace([float("inf"), float("-inf")], 0.0).fillna(0.0) * G_EC
    # [complex] MC_i
    _sum_pay_except = PayI.groupby(df["Timestamp"]).transform("sum") - PayI
    _sum_wd_except = Sum_W_d - W_d
    _w_gs_scaled = W_gs * (1 - q)
    _cost_except = ((_sum_wd_except - _w_gs_scaled) * ToU).where(
    _sum_wd_except > _w_gs_scaled, 0.0
    ) - ((_w_gs_scaled - _sum_wd_except) * FiT).where(_w_gs_scaled > _sum_wd_except, 0.0)
    MC_i = G_EC - (_sum_pay_except - _cost_except)
    # [piecewise] G_CG
    _val_true = (1 - qD) * G_EC / n
    _val_false = (1 + qS) * G_EC / n
    G_CG = _val_true.where(W_net > 0, _val_false).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] CS_EC_avg
    _CS_EC_hourly = CS_EC.groupby(df["Timestamp"]).mean()
    CS_EC_avg = _CS_EC_hourly.mean()
    # [complex] x_EQ
    _W_gs_aligned = df["Timestamp"].map(W_gs).fillna(0.0)
    _denom = W_g + _W_gs_aligned * q
    x_EQ = (G_EQ / _denom).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] CS_i_EQ
    _ratio = G_EQ / PayI
    CS_i_EQ = (_ratio * 100).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] x_G
    _denom = W_g + W_gs * q
    x_G = (G_G / _denom).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] x_C
    _denom = W_g + W_gs * q
    x_C = (G_C / _denom).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] G_MC
    _sum_MC = MC_i.groupby(df["Timestamp"]).transform("sum")
    _ratio = (MC_i / _sum_MC).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    G_MC = (_ratio * G_EC).where(_sum_MC != 0, G_EC / n)
    # [complex] x_CG
    _denom = W_g + W_gs * q
    x_CG = (G_CG / _denom).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] CS_i_CG
    CS_i_CG = (G_CG / PayI * 100).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] FI_EC_EQ_avg
    _sum_x = x_EQ.groupby(df["Timestamp"]).sum()
    _sum_x_sq = (x_EQ ** 2).groupby(df["Timestamp"]).sum()
    _fi_t = (
    ((1 / n) * (_sum_x**2) / _sum_x_sq)
    .replace([float("inf"), float("-inf")], 0.0)
    .fillna(0.0)
    )
    FI_EC_EQ_avg = _fi_t.mean()
    # [complex] FI_EC_G_avg
    _sum_x_G = x_G.groupby(df["Timestamp"]).sum()
    _sum_x_G_sq = (x_G ** 2).groupby(df["Timestamp"]).sum()
    _FI_hourly = (1 / n) * (_sum_x_G ** 2) / _sum_x_G_sq
    _FI_hourly = _FI_hourly.replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    FI_EC_G_avg = pd.Series(_FI_hourly.mean(), index=df.index)
    # [complex] FI_EC_C_avg
    _sum_x = x_C.groupby(df["Timestamp"]).sum()
    _sum_xx = (x_C**2).groupby(df["Timestamp"]).sum()
    _fi = (_sum_x**2) / (n * _sum_xx)
    _fi = _fi.replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    FI_EC_C_avg = pd.Series(_fi.mean(), index=df.index)
    # [complex] x_MC
    _denom = W_g + W_gs * q
    x_MC = (G_MC / _denom).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    # [complex] CS_i_MC
    CS_i_MC = (
    (G_MC / PayI).replace([float("inf"), float("-inf")], 0.0).fillna(0.0) * 100
    )
    # [complex] FI_EC_CG_avg
    _sum_x_CG = x_CG.groupby(df["Timestamp"]).sum()
    _sum_x_CG_sq = (x_CG ** 2).groupby(df["Timestamp"]).sum()
    _FI_EC_CG_t = (
    ((_sum_x_CG**2) / (n * _sum_x_CG_sq))
    .replace([float("inf"), float("-inf")], 0.0)
    .fillna(0.0)
    )
    FI_EC_CG_avg = pd.Series(_FI_EC_CG_t.mean(), index=df.index)
    # [Eq30_EQ] output
    f_EC_EQ = FI_EC_EQ_avg*a + SSI_EC_avg*b*(d_EQ + 1)
    # [complex] FI_EC_MC_avg
    _sum_x = x_MC.groupby(df["Timestamp"]).sum()
    _sum_sq_x = (x_MC**2).groupby(df["Timestamp"]).sum()
    _fi_t = (_sum_x**2).div(n * _sum_sq_x).replace([float("inf"), float("-inf")], 0.0).fillna(0.0)
    FI_EC_MC_avg = _fi_t.mean()
    # [Eq30_CG] output
    f_EC_CG = FI_EC_CG_avg*a + SSI_EC_avg*b*(d_CG + 1)
    # [Eq30_MC] output
    f_EC_MC = FI_EC_MC_avg*a + SSI_EC_avg*b*(d_MC + 1)
    # [complex] optimal_method
    _scores = {"EQ": f_EC_EQ.mean(), "CG": f_EC_CG.mean(), "MC": f_EC_MC.mean()}
    optimal_method = max(_scores, key=_scores.get)
    return {
        "W_d": W_d,
        "W_net": W_net,
        "Wused_i": Wused_i,
        "Wused_EC": Wused_EC,
        "CostI": CostI,
        "RevI_raw": RevI_raw,
        "Sum_W_d": Sum_W_d,
        "qS": qS,
        "qD": qD,
        "SSI_i": SSI_i,
        "SCI_i": SCI_i,
        "SSI_EC": SSI_EC,
        "SCI_EC": SCI_EC,
        "RevI": RevI,
        "Rev_EC": Rev_EC,
        "Cost_EC": Cost_EC,
        "SSI_EC_avg": SSI_EC_avg,
        "SCI_EC_avg": SCI_EC_avg,
        "PayI": PayI,
        "Pay_EC": Pay_EC,
        "Pay_0": Pay_0,
        "G_EC": G_EC,
        "CS_EC": CS_EC,
        "G_EQ": G_EQ,
        "G_G": G_G,
        "G_C": G_C,
        "MC_i": MC_i,
        "G_CG": G_CG,
        "CS_EC_avg": CS_EC_avg,
        "x_EQ": x_EQ,
        "CS_i_EQ": CS_i_EQ,
        "x_G": x_G,
        "x_C": x_C,
        "G_MC": G_MC,
        "x_CG": x_CG,
        "CS_i_CG": CS_i_CG,
        "FI_EC_EQ_avg": FI_EC_EQ_avg,
        "FI_EC_G_avg": FI_EC_G_avg,
        "FI_EC_C_avg": FI_EC_C_avg,
        "x_MC": x_MC,
        "CS_i_MC": CS_i_MC,
        "FI_EC_CG_avg": FI_EC_CG_avg,
        "f_EC_EQ": f_EC_EQ,
        "FI_EC_MC_avg": FI_EC_MC_avg,
        "f_EC_CG": f_EC_CG,
        "f_EC_MC": f_EC_MC,
        "optimal_method": optimal_method,
    }


def _main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", type=Path, required=True)
    ap.add_argument("--tariffs", type=Path, required=True)
    args = ap.parse_args()
    df = pd.read_csv(args.dataset)
    tariffs = pd.read_excel(args.tariffs) if args.tariffs.read_bytes()[:2] == b"PK" else pd.read_csv(args.tariffs)
    results = simulate(df, tariffs, {})
    for k, v in results.items():
        if isinstance(v, (int, float)):
            print(f"  {k:12s} = {v:.4f}")
        elif isinstance(v, pd.Series):
            print(f"  {k:12s}   members={len(v)} sum={v.sum():.4f} mean={v.mean():.4f}")
    print()


if __name__ == "__main__":
    _main()
